
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flashchat_pg
    environment:
      # 設定資料庫的超級管理員帳號與密碼 (本地開發用)
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ming741852
      POSTGRES_DB: flashchat
    ports:
      - "5432:5432" # 開放 5432 讓 Go 可以連進來
        # 電腦重開機時，幫我自動啟動
    volumes:
      - pgdata:/var/lib/postgresql/data # 掛載硬碟，確保資料庫重啟時資料不會不見！

  redis:
    image: redis:7-alpine # 告訴 Docker：去雲端幫我抓第 7 版的輕量級 Redis
    container_name: flashchat_redis
    ports:
      - "6379:6379"  # 把貨櫃裡的 6379 洞口，接上你電腦的 6379 洞

volumes:
  pgdata:
