events {
    worker_connections 1024;
}

http {
    # 🌟 1. 定義背後的伺服器群組 (Upstream)
    upstream chat_servers {
        # host.docker.internal 是一個魔法字眼，讓 Docker 裡的 Nginx 可以連回你本機的 Go 程式
        server host.docker.internal:8081;
        server host.docker.internal:8082;
    }

    server {
        # Nginx 站在門口，監聽 80 通訊埠
        listen 80;

        # 🌟 處理普通的網頁請求 (首頁畫面)
        location / {
            proxy_pass http://chat_servers;
        }
        location /ws {    
            proxy_pass http://chat_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            
            # 把客人的真實 IP 等資訊往後傳
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}